package com.yash.omsapp.model;

import javax.persistence.*;

/**
 * Represents a product category in the Order Management System.
 * Each category has a unique name and an optional description.
 * Used by Admin to organize products.
 */
@Entity
@Table(name = "categories")
public class Category {
	
	/**
     * Unique identifier for the category.
     * Auto-generated by the database.
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	
	/**
     * Name of the category.
     * Must be unique and not null.
     * Maximum length: 120 characters.
     */
	@Column(nullable = false, unique = true, length = 120)
	private String name;

	/**
     * Optional description of the category.
     * Maximum length: 500 characters.
     */
	@Column(length = 500)
	private String description;

	// getters/setters
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
