package com.yash.omsapp.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;


/**
 * Represents a customer's order in the Order Management System.
 * Each order contains customer details, order date, status, total amount,
 * and a list of ordered items.
 */
@Entity
@Table(name = "orders")
public class Order {
	
	/**
     * Unique identifier for the order.
     * Auto-generated by the database.
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	
	/**
     * The customer who placed the order.
     * Mapped as a many-to-one relationship with the User entity.
     */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	private User customer;

	
	/**
     * The date and time when the order was placed.
     * Automatically initialized to the current timestamp.
     */
	@Column(nullable = false)
	private LocalDateTime orderDate = LocalDateTime.now();

	/**
     * Current status of the order.
     * Possible values: PLACED, PAID, SHIPPED, CANCELLED.
     */
	@Column(nullable = false, length = 40)
	private String status = "PLACED"; // PLACED, PAID, SHIPPED, CANCELLED

	/**
     * Total amount of the order.
     * Precision: 12 digits, Scale: 2 decimal places.
     */
	@Column(nullable = false, precision = 12, scale = 2)
	private BigDecimal totalAmount;

	/**
     * List of items included in the order.
     * Mapped as a one-to-many relationship with cascade and orphan removal.
     */
	@OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
	private List<OrderItem> items;

	// getters/setters
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getCustomer() {
		return customer;
	}

	public void setCustomer(User customer) {
		this.customer = customer;
	}

	public LocalDateTime getOrderDate() {
		return orderDate;
	}

	public void setOrderDate(LocalDateTime orderDate) {
		this.orderDate = orderDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public List<OrderItem> getItems() {
		return items;
	}

	public void setItems(List<OrderItem> items) {
		this.items = items;
	}
}
