package com.yash.omsapp.model;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * Represents a product in the Order Management System.
 * Each product belongs to a category and contains details such as name, description,
 * price, stock quantity, and image URL.
 */
@Entity
@Table(name = "products")
public class Product {
	
	/**
     * Unique identifier for the product.
     * Auto-generated by the database.
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
     * Name of the product.
     * Required field with a maximum length of 150 characters.
     */
	@Column(nullable = false, length = 150)
	private String name;
	
	/**
     * Optional description of the product.
     * Maximum length: 1000 characters.
     */
	@Column(length = 1000)
	private String description;
	
	 /**
     * Price of the product.
     * Required field with precision up to 12 digits and 2 decimal places.
     */
	@Column(nullable = false, precision = 12, scale = 2)
	private BigDecimal price;
	

    /**
     * Quantity of the product available in stock.
     * Required field.
     */
	@Column(nullable = false)
	private Integer stockQuantity;
	
	/**
     * URL of the product image.
     * Optional field with a maximum length of 300 characters.
     */
	@Column(length = 300)
	private String imageUrl;

	/**
     * Category to which the product belongs.
     * Required field with eager fetching strategy.
     */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	private Category category;

	// getters/setters
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getStockQuantity() {
		return stockQuantity;
	}

	public void setStockQuantity(Integer stockQuantity) {
		this.stockQuantity = stockQuantity;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}
}
