package com.yash.omsapp.model;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;


/**
 * Represents a user in the Order Management System.
 * Users can have roles such as ADMIN or CUSTOMER and are authenticated via Spring Security.
 */
@Entity
@Table(name = "users")
public class User {
	
	/**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	
	/**
     * Unique username used for login.
     * Cannot be blank and must be unique.
     * Maximum length: 100 characters.
     */
	@Column(unique = true, nullable = false, length = 100)
	@NotBlank
	private String username;

	/**
     * Encrypted password for authentication.
     * Stored with prefix indicating encoding type (e.g., {noop}, {bcrypt}).
     * Maximum length: 200 characters.
     */
	@Column(nullable = false, length = 200)
	private String password; // store with prefix e.g. {noop}password or {bcrypt}...

	/**
     * Role assigned to the user.
     * Can be either "ADMIN" or "CUSTOMER".
     * Maximum length: 20 characters.
     */
	@Column(nullable = false, length = 20)
	private String role; // ADMIN, CUSTOMER

	/**
     * Indicates whether the user account is enabled.
     * Used by Spring Security for access control.
     */
	@Column(nullable = false)
	private boolean enabled = true;

	// getters/setters
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}
}
